// Generated by CoffeeScript 1.7.1
(function() {
  define(['src/basket', 'src/item'], function(Basket, Item) {
    return describe('Basket', function() {
      it('should be defined', function() {
        expect(Basket).toBeDefined();
        return expect(Item).toBeDefined();
      });
      return it('should keep track of distinct items and quantities in basket', function() {
        var basket, laptop, mouse;
        basket = new Basket();
        laptop = new Item(1, 'Laptop', 400);
        mouse = new Item(2, 'Mouse', 30);
        basket.add(laptop);
        expect(basket.totalCount).toEqual(1);
        expect(basket.distinctCount).toEqual(1);
        basket.add(laptop);
        expect(basket.totalCount).toEqual(2);
        return expect(basket.distinctCount).toEqual(1);
      });
    });
  });

}).call(this);
