// Generated by CoffeeScript 1.7.1
(function() {
  define(['libs/jquery/dist/jquery.js', 'src/basket.js', 'src/item.js'], function($, Basket, Item) {
    var basket, laptop, mouse, updateBasket;
    $ = jQuery;
    basket = new Basket();
    laptop = new Item(1, 'Laptop', 400);
    mouse = new Item(2, 'mouse', 40);
    updateBasket = function() {
      var discountAmount, item, total, _i, _len, _ref;
      $('.basketTable tbody').html('');
      total = basket.totalPrice();
      discountAmount = basket.getDiscountInMonetryValue();
      _ref = basket.items;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        $('.basketTable tbody').append("<tr data-item='" + item.item.id + "'><td>" + item.item.title + "</td><td>" + item.quantity + "</td><td>$" + (item.item.price * item.quantity) + "</td><td><i style='cursor:pointer;' class='removeItem glyphicon glyphicon-remove'></i></tr>");
      }
      if (basket.items.length > 0) {
        if (basket.discountAmount > 0) {
          $('.basketTable tbody').append("<tr><td colspan='2'><small>Discount</small></td><td>- $" + (discountAmount.toFixed(2)) + "</td><td colspan='1'></td></tr>");
        }
        $('.basketTable tbody').append("<tr><td colspan='2'><small>Total</small></td><td>$" + (total.toFixed(2)) + "</td><td colspan='1'></td></tr>");
        return $('#discountWrapper').show();
      } else {
        return $('#discountWrapper').hide();
      }
    };
    $('.addToBasket').bind('click', function() {
      var item;
      item = $(this).attr('data-pid') === '1' ? laptop : mouse;
      basket.add(item, parseInt($(this).parent().parent().find('input').val()));
      updateBasket();
      return this;
    });
    $('body').on('click', '.removeItem', function() {
      var item;
      item = $(this).parent().parent().attr('data-item') === '1' ? laptop : mouse;
      basket.remove(item);
      updateBasket();
      return this;
    });
    return $('.discountCode').bind('click', function() {
      basket.addCoupon($("#code").val());
      updateBasket();
      $("#code").val('');
      return this;
    });
  });

}).call(this);
