// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var Basket;
    return Basket = (function() {
      function Basket() {}

      Basket.prototype.items = [];

      Basket.prototype.itemCount = 0;

      Basket.prototype.add = function(item) {
        this.items.push(item);
        return this.itemCount++;
      };

      return Basket;

    })();
  });

}).call(this);
