// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var Item;
    return Item = (function() {
      function Item(id, title, price) {
        this.id = id;
        this.title = title;
        this.price = price;
      }

      return Item;

    })();
  });

}).call(this);
